[package]
name = "image_viewer"
version = "0.1.0"
authors = ["Alexander Hammatt <alexander.hammatt@protonmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]